// Collections (single source of truth)
window.EDELHART_COLLECTIONS = {
    SSS: { name: "SSS", page: "./collections/sss.html" },
    ECHO: { name: "ECHO", page: "./collections/ECHO.html" },
    WA: { name: "Whispering A", page: "./collections/whispering-a.html" },
};

// Products (source of truth)
window.EDELHART_PRODUCTS_CENTRAL = [
    {
        slug: "sss-gold",
        name: "SSS pendant",
        collection: "SSS",
        priceVND: 1996000,
        finalPriceVND: 1996000,
        sale: null,
        images: Array.from({ length: 11 }, (_, i) => `img/products/sss-gold/sss-gold-${i + 1}.jpeg`),
        description: "Shaped in the moment a sea turtle reaches upward toward the chain, the pendant captures a sense of weightlessness—an almost desperate call for help. The blue stone on its shell is crafted with the Encaged Stone technique, allowing it to move freely and mirror the shifting sparkle of sunlight over the ocean.\n",
        availableDesign: {
            materials: ["E silver"],
            stones: ["Swiss Topaz", "Sky Topaz"],
            finishes: ["Gold", "Silver"],
            size: "Consultation",
            chooseMenu: ["E bail", "Basic clasp"],
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        variantLinks: [{ label: "Silver", slug: "sss-silver" }],
        soldOut: false,
    },
    {
        slug: "sss-silver",
        name: "SSS pendant",
        collection: "SSS",
        priceVND: 1996000,
        finalPriceVND: 1996000,
        sale: null,
        images: Array.from({ length: 11 }, (_, i) => `img/products/sss-silver/sss-silver-${i + 1}.jpeg`),
        description: "Shaped in the moment a sea turtle reaches upward toward the chain, the pendant captures a sense of weightlessness—an almost desperate call for help. The blue stone on its shell is crafted with the Encaged Stone technique, allowing it to move freely and mirror the shifting sparkle of sunlight over the ocean.\n",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
            chooseMenu: ["E bail", "Basic clasp"],
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        variantLinks: [{ label: "Gold", slug: "sss-gold" }],
        soldOut: false,
    },
    {
        slug: "squid",
        name: "Squid pendant",
        collection: "SSS",
        priceVND: 2392000,
        finalPriceVND: 2392000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/squid/squid-${i + 1}.jpeg`),
        description: "The design incorporates a meticulously engineered detachable structure, allowing the squid’s tentacles to sway with graceful, lifelike movement.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["Diopside"],
            finishes: ["Gold", "Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "LEGS-pendant",
        name: "LEGS pendant",
        collection: "SSS",
        priceVND: 6146000,
        finalPriceVND: 6146000,
        sale: null,
        images: Array.from({ length: 7 }, (_, i) => `img/products/LEGS-pendant/LEGS-pendant-${i + 1}.jpeg`),
        description: "Combining the refined designs of flush-setting and prong-setting, each gemstone is artfully set to recreate the sparkling illusion of sea foam, brought to life by the graceful movement of diving flippers beneath the water's surface. This design reimagines the beauty of scuba diving in the form of fine jewelry, created with the desire to accompany divers on their adventurous voyages into the mysterious depths of the sea.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz", "Blue Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-female-ring-gold",
        name: "EE ring",
        collection: "SSS",
        priceVND: 2288000,
        finalPriceVND: 2288000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/EE-female-ring-gold/EE-female-ring-gold-${i + 1}.jpeg`),
        description: "A stylised design inspired by the shell of a sea turtle, intentionally crafted so you can layer two to three pieces together with ease.",
        availableDesign: {
            materials: ["E silver", "gold finish"],
            stones: ["Swiss Topaz", "Sky Topaz"],
            finishes: ["Gold"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        variantLinks: [{ label: "Silver", slug: "ee-female-ring-silver" }],
        soldOut: false,
    },
    {
        slug: "ee-female-ring-silver",
        name: "EE ring",
        collection: "SSS",
        priceVND: 2288000,
        finalPriceVND: 2288000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/EE-female-ring-silver/EE-female-ring-silver-${i + 1}.jpeg`),
        description: "A stylised design inspired by the shell of a sea turtle, intentionally crafted so you can layer two to three pieces together with ease.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        variantLinks: [{ label: "Gold", slug: "ee-female-ring-gold" }],
        soldOut: false,
    },
    {
        slug: "ee-female-ring-BR",
        name: "EE ring",
        collection: "SSS",
        priceVND: 2288000, // per your table (2,288,000)
        finalPriceVND: 2288000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/EE-female-ring-BR/EE-female-ring-BR-${i + 1}.jpeg`),
        description: "A stylised design inspired by the shell of a sea turtle, intentionally crafted so you can layer two to three pieces together with ease.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz"],
            finishes: ["Black rhodium"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-male-ring-silver",
        name: "EE male ring",
        collection: "SSS",
        priceVND: 3209000,
        finalPriceVND: 3209000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/EE-male-ring-silver/EE-male-ring-silver-${i + 1}.jpeg`),
        description: "The timeless signet silhouette is reimagined with our signature sea-turtle shell motif.",
        availableDesign: {
            materials: ["E silver"],
            stones: [],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-male-ring-BR",
        name: "EE male ring",
        collection: "SSS",
        priceVND: 3268000,
        finalPriceVND: 3268000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/EE-male-ring-BR/EE-male-ring-BR-${i + 1}.jpeg`),
        description: "The timeless signet silhouette is reimagined with our signature sea-turtle shell motif. And if flawless perfection isn’t what you seek, our antique-inspired black rhodium finish is the perfect choice.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz"],
            finishes: ["Black rhodium"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-male-ring-BR-trap",
        name: "EE male ring",
        collection: "SSS",
        priceVND: 3085000,
        finalPriceVND: 3085000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/EE-male-ring-BR-trap/EE-male-ring-BR-trap-${i + 1}.jpeg`),
        description: "A ring that encapsulates the essence of the entire collection: a stylised sea-turtle shell motif, an encaged-stone technique that creates natural light movement, and an antique-inspired black rhodium finish.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz"],
            finishes: ["Black rhodium"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-female-earring-br",
        name: "EE earring",
        collection: "SSS",
        priceVND: 2784000,
        finalPriceVND: 2784000,
        sale: null,
        images: Array.from({ length: 2 }, (_, i) => `img/products/EE-female-earring-br/EE-female-earring-br-${i + 1}.jpeg`),
        description: "With the encaged-stone technique, the gem is allowed to move freely, capturing and reflecting light from as many angles as possible. From the depths of the ocean come cries for help we cannot hear.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz"],
            finishes: ["Black rhodium"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "earring-shell",
        name: "The Soul Thief pendant",
        collection: "SSS",
        priceVND: 2518000,
        finalPriceVND: 2518000,
        sale: null,
        images: Array.from({ length: 2 }, (_, i) => `img/products/Earring-shell/Earring-shell-${i + 1}.jpeg`),
        description: "The shell and the little hermit to interlock or stand alone, allowing you to wear them as one pendant or as two separate pieces.",
        availableDesign: {
            materials: [],
            stones: [],
            finishes: ["Gold", "Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "earring-blue-gem",
        name: "FOTO earring",
        collection: "SSS",
        priceVND: 5107000,
        finalPriceVND: 5107000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/earring-blue-gem/earring-blue-gem-${i + 1}.jpeg`),
        description: "Each coral branch is hand-carved by the artisan, creating a natural, organic texture. Small blue and white topaz stones are delicately set along the branches, resembling light filtering through the ocean. The branches curve around the central blue stone as if trying to hold onto the deep sea itself.\n",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ring-blue-gem",
        name: "FOTO ring",
        collection: "SSS",
        priceVND: 5645000,
        finalPriceVND: 5645000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/ring-blue-gem/ring-blue-gem-${i + 1}.jpeg`),
        description: "Each coral branch is hand-carved by the artisan, creating a natural, organic texture. Small blue and white topaz stones are delicately set along the branches, resembling light filtering through the ocean. The branches curve around the central blue stone as if trying to hold onto the deep sea itself.\n",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "necklace-blue-gem",
        name: "FOTO necklace",
        collection: "SSS",
        priceVND: 15378000,
        finalPriceVND: 15378000,
        sale: null,
        images: Array.from({ length: 7 }, (_, i) => `img/products/necklace-blue-gem/necklace-blue-gem-${i + 1}.jpeg`),
        description: "Each coral branch is hand-carved by the artisan, creating a natural, organic texture. Small blue and white topaz stones are delicately set along the branches, resembling light filtering through the ocean. The branches curve around the central blue stone as if trying to hold onto the deep sea itself.\n",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "stingray-gold",
        name: "The Magic Carpet necklace",
        collection: "SSS",
        priceVND: 9612000,
        finalPriceVND: 9612000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/stingray-gold/stingray-gold-${i + 1}.jpeg`),
        description: "It is truly a magic carpet of the ocean, rendered in metal through the refined craftsmanship of our jewellers.",
        availableDesign: {
            materials: ["E silver"],
            stones: [],
            finishes: ["Gold"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ring-gold-multi-gems",
        name: "Bluefall ring",
        collection: "ECHO",
        priceVND: 7426000,
        finalPriceVND: 7426000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/ring-gold-multi-gems/ring-gold-multi-gems-${i + 1}.jpeg`),
        description: "Inspired by the gentle flow of a waterfall, Bluefall blends blue and white stones to create depth and a natural shimmer. The design combines flush-setting and prong-setting, allowing each stone to catch light from multiple angles. With its intentional mix of dense and open placements, the stones appear to cascade across the ring, forming a refined sense of movement.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz", "Blue Topaz"],
            finishes: ["Gold"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ring-chameleon",
        name: "Chameleon ring",
        collection: "ECHO",
        priceVND: 6129000,
        finalPriceVND: 6129000,
        sale: null,
        images: Array.from({ length: 2 }, (_, i) => `img/products/ring-chameleon/ring-chameleon-${i + 1}.jpeg`),
        description: "Our signature “encaged stone” technique is carefully engineered so each stone remains visible while having the freedom to move and shimmer naturally. Every detail is refined to ensure the stone stays protected from scratches despite its continuous movement.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["Sapphire", "Spinel"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "necklace-ants",
        name: "Whispering Artist necklace",
        collection: "WA",
        priceVND: 3909000,
        finalPriceVND: 3909000,
        sale: null,
        images: Array.from({ length: 6 }, (_, i) => `img/products/necklace-ants/necklace-ants-${i + 1}.jpeg`),
        description: "Inspired by the quiet dedication and passion of Edelhart’s goldsmiths — the ‘ants’ of our craft, tirelessly working not just for a living but to breathe life into the beauty we continually pursue.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["Sapphire", "Spinel"],
            finishes: ["Black rhodium", "Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
            notes: "Chain Options Consultation", // special CTA
        },
        soldOut: false,
    },
];

window.EDELHART_CONFIG = {
    recommended: {
        pinned: ["LEGS-pendant", "sss-gold", "ee-male-ring-silver"],
        pool: [
            "ee-female-ring-gold",
            "ring-blue-gem",
            "earring-blue-gem",
            "necklace-blue-gem",
            "ee-male-ring-BR",
            "squid",
            "stingray-gold",
            "ee-male-ring-BR-trap",
            "sss-silver",
            "ee-female-ring-silver",
            "ring-chameleon",
        ],
    },
    related: {
        pinnedBySlug: {
            "sss-gold": ["sss-silver", "stingray-gold"],
            "sss-silver": ["sss-gold", "stingray-gold"],
            "LEGS-pendant": ["ee-female-ring-gold", "ee-male-ring-BR"],
        },
        pool: [
            "sss-gold",
            "sss-silver",
            "LEGS-pendant",
            "ee-female-ring-gold",
            "ee-female-ring-silver",
            "ee-female-ring-BR",
            "ee-male-ring-silver",
            "ee-male-ring-BR",
            "ee-male-ring-BR-trap",
            "ring-blue-gem",
            "earring-blue-gem",
            "necklace-blue-gem",
            "ring-chameleon",
            "necklace-ants",
            "earring-shell",
            "squid",
            "stingray-gold",
            "ring-gold-multi-gems",
        ],
    },
};

window.EDELHART_PRODUCT_PAGES = {
    "sss-gold": "products/sss-pendant-gold.html",
    "sss-silver": "products/sss-pendant-silver.html",
    "squid": "products/squid.html",
    "LEGS-pendant": "products/legs-pendant.html",
    "ee-female-ring-gold": "products/ee-female-ring-gold.html",
    "ee-female-ring-silver": "products/ee-female-ring-silver.html",
    "ee-female-ring-BR": "products/ee-female-ring-black-rhodium.html",
    "ee-male-ring-silver": "products/ee-male-ring-silver.html",
    "ee-male-ring-BR": "products/ee-male-ring-black-rhodium.html",
    "ee-male-ring-BR-trap": "products/ee-male-ring-black-rhodium-stone.html",
    "ee-female-earring-br": "products/ee-female-earring-br.html",
    "earring-shell": "products/earring-shell.html",
    "earring-blue-gem": "products/earring-blue-gem.html",
    "ring-blue-gem": "products/ring-blue-gem.html",
    "necklace-blue-gem": "products/necklace-blue-gem.html",
    "stingray-gold": "products/stingray-gold.html",
    "ring-gold-multi-gems": "products/Bluefall ring.html",
    "ring-chameleon": "products/ring-chameleon.html",
    "necklace-ants": "products/necklace-ants.html",
    "11": "products/11.html",
};

window.EDELHART_PRODUCTS = (window.EDELHART_PRODUCTS_CENTRAL || []).map((p) => ({
    slug: p.slug,
    name: p.name,
    title: p.name,
    collection: p.collection,
    material: p.availableDesign ? (p.availableDesign.materials || []).join(", ") : "",
    priceVND: p.finalPriceVND,
    images: p.images || [],
    view: window.EDELHART_PRODUCT_PAGES[p.slug] || `products/${p.slug}.html`,
    meta: p.availableDesign ? (p.availableDesign.finishes || []).join(", ") : "",
}));