// Collections (single source of truth)
window.EDELHART_COLLECTIONS = {
    SSS: { name: "SSS", page: "./collections/sss.html" },
    ECHO: { name: "ECHO", page: "./collections/ECHO.html" },
    WA: { name: "Whispering A", page: "./collections/whispering-a.html" },
};

// Products (source of truth)
window.EDELHART_PRODUCTS_CENTRAL = [
    {
        slug: "sss-gold",
        name: "SSS pendant — gold",
        collection: "SSS",
        priceVND: 1996000,
        finalPriceVND: 1996000,
        sale: null,
        images: Array.from({ length: 11 }, (_, i) => `img/products/sss-gold/sss-gold-${i + 1}.jpeg`),
        description: "The SSS pendant embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in gold — limited stock. Signature design for the collection.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["Swiss Topaz", "Sky Topaz"],
            finishes: ["Gold", "Silver"],
            size: "Consultation",
            chooseMenu: ["E bail", "Basic clasp"],
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        variantLinks: [{ label: "Silver", slug: "sss-silver" }],
        soldOut: false,
    },
    {
        slug: "sss-silver",
        name: "SSS pendant — silver",
        collection: "SSS",
        priceVND: 1996000,
        finalPriceVND: 1996000,
        sale: null,
        images: Array.from({ length: 11 }, (_, i) => `img/products/sss-silver/sss-silver-${i + 1}.jpeg`),
        description: "The SSS pendant embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in sterling silver — signature design with clean lines. Everyday elegance.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
            chooseMenu: ["E bail", "Basic clasp"],
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        variantLinks: [{ label: "Gold", slug: "sss-gold" }],
        soldOut: false,
    },
    {
        slug: "squid",
        name: "Squid",
        collection: "SSS",
        priceVND: 2392000,
        finalPriceVND: 2392000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/squid/squid-${i + 1}.jpeg`),
        description: "The Squid embodies our signature aesthetic — refined minimalism with a statement edge. Crafted with organic, fluid silhouette, this piece is unique for statement wear.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["Diopside"],
            finishes: ["Gold", "Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "LEGS-pendant",
        name: "LEGS pendant",
        collection: "SSS",
        priceVND: 6146000,
        finalPriceVND: 6146000,
        sale: null,
        images: Array.from({ length: 7 }, (_, i) => `img/products/LEGS-pendant/LEGS-pendant-${i + 1}.jpeg`),
        description: "The LEGS pendant embodies our signature aesthetic — refined minimalism with a statement edge. Crafted as a sculptural silhouette with dynamic form, this piece is bold for layered necklaces.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz", "Blue Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-female-ring-gold",
        name: "EE female ring — gold",
        collection: "SSS",
        priceVND: 2288000,
        finalPriceVND: 2288000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/EE-female-ring-gold/EE-female-ring-gold-${i + 1}.jpeg`),
        description: "The EE female ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in gold with elegant finish and the signature EE profile, this piece features comfortable taper for daily wear.",
        availableDesign: {
            materials: ["E silver", "gold finish"],
            stones: ["Swiss Topaz", "Sky Topaz"],
            finishes: ["Gold"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        variantLinks: [{ label: "Silver", slug: "ee-female-ring-silver" }],
        soldOut: false,
    },
    {
        slug: "ee-female-ring-silver",
        name: "EE female ring — silver",
        collection: "SSS",
        priceVND: 2288000,
        finalPriceVND: 2288000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/EE-female-ring-silver/EE-female-ring-silver-${i + 1}.jpeg`),
        description: "The EE female ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in sterling silver with a luminous finish, this piece features balanced weight and clean form.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        variantLinks: [{ label: "Gold", slug: "ee-female-ring-gold" }],
        soldOut: false,
    },
    {
        slug: "ee-female-ring-BR",
        name: "EE female ring — black rhodium",
        collection: "SSS",
        priceVND: 2288000, // per your table (2,288,000)
        finalPriceVND: 2288000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/EE-female-ring-BR/EE-female-ring-BR-${i + 1}.jpeg`),
        description: "The EE female ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in black rhodium with bold dark finish, this piece features signature design for everyday elegance.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz"],
            finishes: ["Black rhodium"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-male-ring-silver",
        name: "EE male ring — silver",
        collection: "SSS",
        priceVND: 3209000,
        finalPriceVND: 3209000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/EE-male-ring-silver/EE-male-ring-silver-${i + 1}.jpeg`),
        description: "The EE male ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in sterling silver with a luminous finish, this piece features balanced weight and clean form.",
        availableDesign: {
            materials: ["E silver"],
            stones: [],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-male-ring-BR",
        name: "EE male ring — black rhodium",
        collection: "SSS",
        priceVND: 3268000,
        finalPriceVND: 3268000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/EE-male-ring-BR/EE-male-ring-BR-${i + 1}.jpeg`),
        description: "The EE male ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in black rhodium with bold dark finish and high contrast edges, this piece features limited oxidation wear for character.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz"],
            finishes: ["Black rhodium"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-male-ring-BR-trap",
        name: "EE male ring — black rhodium (Stone trapping)",
        collection: "SSS",
        priceVND: 3085000,
        finalPriceVND: 3085000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/EE-male-ring-BR-trap/EE-male-ring-BR-trap-${i + 1}.jpeg`),
        description: "The EE male ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in black rhodium with stone trapping, this piece features bold design and versatile finish.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz"],
            finishes: ["Black rhodium"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ee-female-earring-br",
        name: "EE female earring — black rhodium",
        collection: "SSS",
        priceVND: 2784000,
        finalPriceVND: 2784000,
        sale: null,
        images: Array.from({ length: 2 }, (_, i) => `img/products/EE-female-earring-br/EE-female-earring-br-${i + 1}.jpeg`),
        description: "The EE female earring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted in black rhodium with bold dark finish, this piece features signature design for everyday elegance.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz"],
            finishes: ["Black rhodium"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "earring-shell",
        name: "Shell earring",
        collection: "SSS",
        priceVND: 2518000,
        finalPriceVND: 2518000,
        sale: null,
        images: Array.from({ length: 2 }, (_, i) => `img/products/Earring-shell/Earring-shell-${i + 1}.jpeg`),
        description: "Soul Thief — sea-inspired form with organic, fluid silhouette.",
        availableDesign: {
            materials: [],
            stones: [],
            finishes: ["Gold", "Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "earring-blue-gem",
        name: "FOTO earring",
        collection: "SSS",
        priceVND: 5107000,
        finalPriceVND: 5107000,
        sale: null,
        images: Array.from({ length: 5 }, (_, i) => `img/products/earring-blue-gem/earring-blue-gem-${i + 1}.jpeg`),
        description: "The FOTO earring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted with icy blue focal stone, this piece is unique for statement wear.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ring-blue-gem",
        name: "FOTO ring",
        collection: "SSS",
        priceVND: 5645000,
        finalPriceVND: 5645000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/ring-blue-gem/ring-blue-gem-${i + 1}.jpeg`),
        description: "The FOTO ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted with sculpted band with blue gem, this piece is unique for statement wear.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "necklace-blue-gem",
        name: "Blue gemstone necklace",
        collection: "SSS",
        priceVND: 15378000,
        finalPriceVND: 15378000,
        sale: null,
        images: Array.from({ length: 7 }, (_, i) => `img/products/necklace-blue-gem/necklace-blue-gem-${i + 1}.jpeg`),
        description: "The Blue gemstone necklace — layer-friendly centerpiece with London Topaz.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["London Topaz"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "stingray-gold",
        name: "Stingray — gold",
        collection: "SSS",
        priceVND: 9612000,          // consultation until filled
        finalPriceVND: 9612000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/stingray-gold/stingray-gold-${i + 1}.jpeg`),
        description: "The Stingray — gold embodies our signature aesthetic — refined minimalism with a statement edge.",
        availableDesign: {
            materials: ["E silver"],
            stones: [],
            finishes: ["Gold"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ring-gold-multi-gems",
        name: "Bluefall ring",
        collection: "ECHO",
        priceVND: 7426000,
        finalPriceVND: 7426000,
        sale: null,
        images: Array.from({ length: 4 }, (_, i) => `img/products/ring-gold-multi-gems/ring-gold-multi-gems-${i + 1}.jpeg`),
        description: "The Bluefall ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted with playful spectrum of stones.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["White Topaz", "Blue Topaz"],
            finishes: ["Gold"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "ring-chameleon",
        name: "Chameleon ring",
        collection: "ECHO",
        priceVND: 6129000,
        finalPriceVND: 6129000,
        sale: null,
        images: Array.from({ length: 2 }, (_, i) => `img/products/ring-chameleon/ring-chameleon-${i + 1}.jpeg`),
        description: "The Chameleon ring embodies our signature aesthetic — refined minimalism with a statement edge. Crafted with changing, shifting contours.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["Sapphire", "Spinel"],
            finishes: ["Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
        },
        soldOut: false,
    },
    {
        slug: "necklace-ants",
        name: "Ants necklace",
        collection: "WA",
        priceVND: 3909000,
        finalPriceVND: 3909000,
        sale: null,
        images: Array.from({ length: 6 }, (_, i) => `img/products/necklace-ants/necklace-ants-${i + 1}.jpeg`),
        description: "The Ants necklace — rhythmic chain of tiny forms. Statement yet refined.",
        availableDesign: {
            materials: ["E silver"],
            stones: ["Sapphire", "Spinel"],
            finishes: ["Black rhodium", "Silver"],
            size: "Consultation",
        },
        bespokeDesign: {
            metals: ["E silver", "10K gold", "14K gold", "18K gold"],
            stoneMenu: ["Gemstones", "Diamond"],
            finishes: ["Silver", "Gold", "Black rhodium"],
            size: "Consultation",
            notes: "Chain Options Consultation", // special CTA
        },
        soldOut: false,
    },
];

window.EDELHART_CONFIG = {
    recommended: {
        pinned: ["LEGS-pendant", "sss-gold", "ee-male-ring-silver"],
        pool: [
            "ee-female-ring-gold",
            "ring-blue-gem",
            "earring-blue-gem",
            "necklace-blue-gem",
            "ee-male-ring-BR",
            "squid",
            "stingray-gold",
            "ee-male-ring-BR-trap",
            "sss-silver",
            "ee-female-ring-silver",
            "ring-chameleon",
        ],
    },
    related: {
        pinnedBySlug: {
            "sss-gold": ["sss-silver", "stingray-gold"],
            "sss-silver": ["sss-gold", "stingray-gold"],
            "LEGS-pendant": ["ee-female-ring-gold", "ee-male-ring-BR"],
        },
        pool: [
            "sss-gold",
            "sss-silver",
            "LEGS-pendant",
            "ee-female-ring-gold",
            "ee-female-ring-silver",
            "ee-female-ring-BR",
            "ee-male-ring-silver",
            "ee-male-ring-BR",
            "ee-male-ring-BR-trap",
            "ring-blue-gem",
            "earring-blue-gem",
            "necklace-blue-gem",
            "ring-chameleon",
            "necklace-ants",
            "earring-shell",
            "squid",
            "stingray-gold",
            "ring-gold-multi-gems",
        ],
    },
};

window.EDELHART_PRODUCT_PAGES = {
    "sss-gold": "products/sss-pendant-gold.html",
    "sss-silver": "products/sss-pendant-silver.html",
    "squid": "products/squid.html",
    "LEGS-pendant": "products/legs-pendant.html",
    "ee-female-ring-gold": "products/ee-female-ring-gold.html",
    "ee-female-ring-silver": "products/ee-female-ring-silver.html",
    "ee-female-ring-BR": "products/ee-female-ring-black-rhodium.html",
    "ee-male-ring-silver": "products/ee-male-ring-silver.html",
    "ee-male-ring-BR": "products/ee-male-ring-black-rhodium.html",
    "ee-male-ring-BR-trap": "products/ee-male-ring-black-rhodium-stone.html",
    "ee-female-earring-br": "products/ee-female-earring-br.html",
    "earring-shell": "products/earring-shell.html",
    "earring-blue-gem": "products/earring-blue-gem.html",
    "ring-blue-gem": "products/ring-blue-gem.html",
    "necklace-blue-gem": "products/necklace-blue-gem.html",
    "stingray-gold": "products/stingray-gold.html",
    "ring-gold-multi-gems": "products/Bluefall ring.html",
    "ring-chameleon": "products/ring-chameleon.html",
    "necklace-ants": "products/necklace-ants.html",
    "11": "products/11.html",
};

window.EDELHART_PRODUCTS = (window.EDELHART_PRODUCTS_CENTRAL || []).map((p) => ({
    slug: p.slug,
    name: p.name,
    title: p.name,
    collection: p.collection,
    material: p.availableDesign ? (p.availableDesign.materials || []).join(", ") : "",
    priceVND: p.finalPriceVND,
    images: p.images || [],
    view: window.EDELHART_PRODUCT_PAGES[p.slug] || `products/${p.slug}.html`,
    meta: p.availableDesign ? (p.availableDesign.finishes || []).join(", ") : "",
}));